### ISSUE TITLE
ERROR in ./node_modules/3d-force-graph/dist/3d-force-graph.module.js Module build failed (from ./node_modules/babel-loader/lib/index.js)

### ISSUE THREAD

**Issue by oshihirii** [vasturiano/3d-force-graph#129]
Hello,

Just having some problems  building with webpack.    

Version:  `"3d-force-graph": "^1.39.0"`
OS:   Windows 10 Pro

**Error:**   
```
ERROR in ./node_modules/3d-force-graph/dist/3d-force-graph.module.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
ReferenceError: Unknown plugin "external-helpers" specified in "C:\\path\\to\\my\\folder\\node_modules\\3d-force-graph\\.babelrc" at 0, attempted to resolve relative to "C:\\path\\to\\my\\folder\\node_modules\\3d-force-graph"
    at C:\path\to\my\folder\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (C:\path\to\my\folder\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\path\to\my\folder\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\path\to\my\folder\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\path\to\my\folder\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\path\to\my\folder\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\path\to\my\folder\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\path\to\my\folder\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (C:\path\to\my\folder\node_modules\babel-loader\lib\index.js:173:20)
 @ ./src/js/common.js 79:19-44
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! showcase@1.0.0 webpack: `webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the showcase@1.0.0 webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Steps to replicate**

    import ForceGraph3D from '3d-force-graph';

**.babelrc**

```js
{
	"presets": [
		"env",
		"stage-0"
	]
}
```

**webpack.config.js**

```js
const path = require('path');
const UglifyJsPlugin = require("uglifyjs-webpack-plugin"); 

var webpack = require("webpack");

console.log("the __dirname is: " + __dirname);

module.exports = {
    mode: "development", 
    entry: "./src/js/common.js",
    output: {
        filename: "bundle.js",
        path: path.resolve(__dirname, "dist/js")
    },
    module: {
        rules: [{
                test: /\.js$/,
                // exclude: /(node_modules)/,
                use: {
                    loader: "babel-loader",
                    options: {
                        presets: ["env", "stage-0"]
                    }
                }
            },
            {
                test: /\.css$/,
                use: [
                    { loader: "style-loader" },
                    { loader: "css-loader" }
                ]
            },
            {
                test: /\.less$/,
                use: [
                    { loader: "style-loader" },
                    { loader: "css-loader" },
                    { loader: "less-loader" }
                ]
            },
            {
                test: /\.jpg$/,
                use: [
                    { loader: "url-loader" }
                ]
            },
            {
            test: require.resolve('jquery'),
            use: [{
            loader: 'expose-loader',
            options: '$'
            }]
            },
            {
            test: require.resolve('js-cookie'),
            use: [{
            loader: 'expose-loader',
            options: 'Cookies'
            }]
            }
        ]
    },
    plugins: [
       new UglifyJsPlugin(),
       new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery"
        })
    ],
    resolve: {
    alias: {
        'uikit-util': path.resolve(__dirname, 'node_modules/uikit/src/js/util')
    }
    }
}
```

**JS**

Just using the [basic example](https://github.com/vasturiano/3d-force-graph/blob/master/example/basic/index.html):

```js
// Random tree
const N = 300;
const myData = {
  nodes: [...Array(N).keys()].map(i => ({ id: i })),
  links: [...Array(N).keys()]
    .filter(id => id)
    .map(id => ({
      source: id,
      target: Math.round(Math.random() * (id-1))
    }))
};

const myGraph = ForceGraph3D();

myGraph(document.getElementById('graph'))
.graphData(myData);
```
Thank you.

**Comment by oshihirii** [comment]
I tried setting 'mode: production' in `webpack.config.js` per this thread, but I get the same errors:

https://github.com/selfrefactor/rambda/issues/60

**Comment by oshihirii** [comment]
I also tried this:

    npm install --save-dev @babel/plugin-external-helpers

from  https://www.npmjs.com/package/@babel/plugin-external-helpers

and get the same errors.

**Comment by oshihirii** [comment]
I did this from `C:\path\to\my\folder\node_modules\3d-force-graph\`:

    npm install

And then tried to run webpack again and now get more errors:

```
$ npm run webpack

> showcase@1.0.0 webpack C:\path\to\my\folder
> webpack

the __dirname is: C:\path\to\my\folder
[BABEL] Note: The code generator has deoptimised the styling of "C:/path/to/my/foldernode_modules/3d-force-graph/node_modules/three/build/three.module.js" as it exceeds the max of "500KB".
Hash: 34ca3b37ff1f6af857a6
Version: webpack 4.19.1
Time: 30164ms
Built at: 2018-10-13 19:31:22
    Asset     Size  Chunks             Chunk Names
bundle.js  4.1 MiB    main  [emitted]  main
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 823 bytes {main} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 521 bytes {main} [built]
[./src/css/colorjoe.css] 1.07 KiB {main} [built]
[./src/css/custom_uikit_theme/toolstheme.less] 1.22 KiB {main} [built]
[./src/css/datepicker.min.css] 1.08 KiB {main} [built]
[./src/css/float-labels.css] 1.08 KiB {main} [built]
[./src/css/hybrid.css] 1.06 KiB {main} [built]
[./src/js/colorjoe.js] 31.4 KiB {main} [built]
[./src/js/common.js] 224 KiB {main} [built]
[./src/js/datepicker.esm.js] 38.4 KiB {main} [built]
[./src/js/float-labels.js] 10.6 KiB {main} [built]
[./src/js/highlight.min.js] 52.5 KiB {main} [built]
[./src/js/jquery.autocomplete.js] 32.9 KiB {main} [built]
[./src/js/jquery.loadingdotdotdot.js] 1.98 KiB {main} [built]
[./src/js/uikit.js] 2.04 KiB {main} [built]
    + 414 hidden modules

ERROR in ./node_modules/3d-force-graph/node_modules/accessor-fn/dist/accessor.min.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
ReferenceError: Unknown plugin "add-module-exports" specified in "C:\\path\\to\\my\\folder\\node_modules\\3d-force-graph\\node_modules\\accessor-fn\\.babelrc" at 0, attempted to resolve relative to "C:\\path\\to\\my\\folder\\node_modules\\3d-force-graph\\node_modules\\accessor-fn"
    at C:\path\to\my\folder\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (C:\path\to\my\folder\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\path\to\my\folder\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\path\to\my\folder\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\path\to\my\folder\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\path\to\my\folder\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\path\to\my\folder\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\path\to\my\folder\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (C:\path\to\my\folder\node_modules\babel-loader\lib\index.js:173:20)
 @ ./node_modules/3d-force-graph/dist/3d-force-graph.module.js 21:18-40
 @ ./src/js/common.js

ERROR in ./node_modules/3d-force-graph/node_modules/kapsule/dist/kapsule.min.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
ReferenceError: Unknown plugin "add-module-exports" specified in "C:\\path\\to\\my\\folder\\node_modules\\3d-force-graph\\node_modules\\kapsule\\.babelrc" at 0, attempted to resolve relative to "C:\\path\\to\\my\\folder\\node_modules\\3d-force-graph\\node_modules\\kapsule"
    at C:\path\to\my\folder\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (C:\path\to\my\folder\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\path\to\my\folder\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\path\to\my\folder\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\path\to\my\folder\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\path\to\my\folder\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\path\to\my\folder\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\path\to\my\folder\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (C:\path\to\my\folder\node_modules\babel-loader\lib\index.js:173:20)
 @ ./node_modules/3d-force-graph/dist/3d-force-graph.module.js 25:15-33
 @ ./src/js/common.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! showcase@1.0.0 webpack: `webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the showcase@1.0.0 webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by vasturiano** [comment]
@oshihirii I think you are trying to transpile the library. In your webpack config I see this:
```
// exclude: /(node_modules)/,
```

Generally it's disadvised to transpile any `node_modules` code. Plus, this `3d-force-graph.module.js` doesn't need to since it's already ES5 compatible.

**Comment by oshihirii** [comment]
thank you very much @vasturiano , when i uncomment out that line, the webpack build works correctly - there was some reason i commented out that line (to get some other library working i think), but i can't remember what.  thanks again!
