### ISSUE TITLE
Cannot read property 'forEach' of undefined, Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by EmmaU25** [vasturiano/3d-force-graph#36]
Hello Vasturiano

this is my code:

```
var trans = [];
var ets = [];
var gData;


//Fonction pour creer un object de type automate
class Automate{
  constructor(){
    this.nodes = [];
    this.links = [];
    
    }
}

class Etat {
  constructor(id){
    this.id = id;
  }
}

class Transition {
  constructor(des,txt, color, next){
    this.source = des;
    this.txt = txt;
    this.color = color;
    this.target = next  
  }
}
//Fonction pour telecharger le fichier
function uploadFile(e) {
  var file = e.target.files[0];
  if (!file) {
    return;
  }
  var read = new FileReader();
  read.onload = function(e) {
    var content = e.target.result;
    gData = parseContent(content);
  };
  read.readAsText(file);
}

function validateEtat(eta){
  var flag = false;
  for (var i = 0; i < ets.length; i++) {
    if(ets[i].id === eta){
      flag = true;
    }
  }

  if(!flag){
    const eti = new Etat(eta);
    ets.push(eti);
  }
}

//Fonction pour parser les donnés TXT en JSON
function parseContent(content) {
    //Couper chaque ligne du fichier aprés saut de ligne
    var lines = content.split("\n");
    //Creation de l'automate
    var automateObject;
    //Parcourir tout le fichier
    for (var i = 0; i < lines.length-1; i++) {
      //Pour creer l'onbjet automate
        if(i == 0){
          var currentline = lines[i].split("\n");
          currentline = lines[i].replace(/[\(\)]/g, '');  
          currentline = currentline.replace(/,/g, '');   
          currentline = currentline.split(" ");
          automateObject = new Automate();
          const eta = new Etat(parseInt(currentline[1]));
          //ets.push(parseInt(currentline[1]));
        } else {
          //variable pour stocker le titre et la couleur
          var label;
          //variable pour couper chaque ligne du fichier
          var currentline = lines[i].split("\n");
            //Enlever les parenthese de la chaine de characters
            currentline = lines[i].replace(/[\(\)]/g, '');
            //Enlever les citations de la chaine
            currentline = currentline.replace(/['"]+/g, '');
            //Couper la chaine en 3 morceaux
            currentline = currentline.split(",",3);
            //Couper le deuxieme atribut pour obtenir le nom de lien et la couleur
            label = currentline[1].split(":");
            //Creation d'un object de type automate
            const tran = new Transition(parseInt(currentline[0]),label[0],label[1],parseInt(currentline[2]));
            //Ajouter l'object dans l'array
            trans.push(tran);
            validateEtat(parseInt(currentline[0]));
            validateEtat(parseInt(currentline[2]));

        }
    }
automateObject.nodes = ets; 
automateObject.links = trans;

console.log(JSON.stringify(automateObject))        
return JSON.stringify(automateObject);
}


function dessiner(){
  const Graph = ForceGraph3D()
      (document.getElementById('3d-graph'))
        .graphData(gData);
}

//Asignation d'un event au bouton du fichier HTML
document.getElementById('file-input')
  .addEventListener('change', uploadFile, false);
```

and this is my index

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Test lire txt</title>

  </head>
  <body>
    <input type="file" id="file-input" />
    <button onclick="dessiner()">Print</button>
    <div id="3d-graph"></div>
    <script src="https://unpkg.com/3d-force-graph@1.25.1/dist/3d-force-graph.min.js"></script>
	<script src="main.js"></script>
	
  </body>
</html>
```
but when you click on the button, the console will display the following error

> Uncaught TypeError: Cannot read property 'forEach' of undefined
>     at https://unpkg.com/3d-force-graph@1.25.1/dist/3d-force-graph.min.js:5:105009
>     at Function.tickFrame (https://unpkg.com/3d-force-graph@1.25.1/dist/3d-force-graph.min.js:5:105368)
>     at Function.r.(anonymous function) [as tickFrame] (https://unpkg.com/3d-force-graph@1.25.1/dist/3d-force-graph.min.js:5:91735)
>     at i.r.(anonymous function) [as tickFrame] (https://unpkg.com/3d-force-graph@1.25.1/dist/3d-force-graph.min.js:5:102665)
>     at t (https://unpkg.com/3d-force-graph@1.25.1/dist/3d-force-graph.min.js:5:119228)

and

> Uncaught TypeError: Cannot read property 'length' of undefined
>     at Function.update (3d-force-graph.min.js:5)
>     at 3d-force-graph.min.js:5
>     at c (3d-force-graph.min.js:5)

the data that I pass is like
{"links":[{"source":0,"txt":" X","color":"BLACK","target":1},{"source":0,"txt":" X","color":"GREEN","target":2},{"source":1,"txt":" X","color":"BLACK","target":3},{"source":2,"txt":" Y","color":"GREEN","target":1},{"source":3,"txt":" X","color":"BLACK","target":1},{"source":3,"txt":" X","color":"GREEN","target":4},{"source":4,"txt":" Y","color":"GREEN","target":2},{"source":4,"txt":" X","color":"GREEN","target":5},{"source":5,"txt":" Y","color":"GREEN","target":6}],"nodes":[{"id":0},{"id":1},{"id":2},{"id":3},{"id":4},{"id":5},{"id":6}]}

**Comment by vasturiano** [comment]
Hi @EmmaU25, it seems the error you're having is in the loading application and unrelated to 3d-force-graph. I've tried just the graph section with your data and it seems to work as intended:
```
<body>
  <script src="https://unpkg.com/3d-force-graph"></script>

  <div id="3d-graph"></div>

  <script>
    const data = {"links":[{"source":0,"txt":" X","color":"BLACK","target":1},{"source":0,"txt":" X","color":"GREEN","target":2},{"source":1,"txt":" X","color":"BLACK","target":3},{"source":2,"txt":" Y","color":"GREEN","target":1},{"source":3,"txt":" X","color":"BLACK","target":1},{"source":3,"txt":" X","color":"GREEN","target":4},{"source":4,"txt":" Y","color":"GREEN","target":2},{"source":4,"txt":" X","color":"GREEN","target":5},{"source":5,"txt":" Y","color":"GREEN","target":6}],"nodes":[{"id":0},{"id":1},{"id":2},{"id":3},{"id":4},{"id":5},{"id":6}]};

    ForceGraph3D()
      (document.getElementById('3d-graph'))
        .graphData(data);
  </script>
</body>
```

**Comment by EmmaU25** [comment]
But the way in which I pass the variable to 3d-force-graph is fine?
