### ISSUE TITLE
Bloom Effect breaks the 3d force graph

### ISSUE THREAD

**Issue by chunw** [vasturiano/3d-force-graph#566]
**Describe the bug**
Bloom Effect breaks the entire 3D force graph. e.g. The page https://vasturiano.github.io/3d-force-graph/example/bloom-effect/ is broken. 

Browser console error:
3d-force-graph:2 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at 3d-force-graph:2:388064
    at ga.renderBufferDirect (3d-force-graph:2:388240)
    at Ue (3d-force-graph:2:391915)
    at Fe (3d-force-graph:2:391528)
    at ze (3d-force-graph:2:391173)
    at ga.render (3d-force-graph:2:395534)
    at FullScreenQuad.render (Pass.js:32:14)
    at UnrealBloomPass.render (UnrealBloomPass.js:143:17)
    at Nf.render (3d-force-graph:5:61694)
    at Function.tick (3d-force-graph:5:94721)

**Expected behavior**
This demo used to load.

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Browser [e.g. chrome, safari, firefox]

**Smartphone (please complete the following information):**
 - Device: [iPhone8]
 - Browser [e.g. safari]

**Comment by riita10069** [comment]
+1

**Comment by Coresummer** [comment]
+1
